name: Download cross workflow artifact on master

on:
  push:
    branches:
      - master

jobs:
  download-cross-workflow-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get PR info
        id: get_pr_info
        uses: actions/github-script@v2
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/get-pr-info.js');
            await require(scriptPath)(github, context, core);
      - name: Display PR info
        run: |
          echo "PR outputs - ${{ steps.get_pr_info.outputs }}"
          echo "PR number - ${{ steps.get_pr_info.outputs.prNumber }}"
      - name: Download artifact once PR merged
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr-upload-data.yml
          name: data-arctifact
          pr: ${{ steps.get_pr_info.outputs.prNumber }}
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Collect data
        id: collect_data
        run: echo "::set-output name=downloadedData::$(node ./.github/workflows/download-cross-workflow-artifact.js)"
      - name: Post results to Log console
        run: echo "The downloaded ramdom number is ${{ steps.collect_data.outputs.downloadedData }}"
