name: pr-dependabot

on:
  workflow_run:
    workflows: ["pr-upload-data"]
    branches: [master]
    types:
      - completed

jobs:
  dependabot-comments:
    # if: github.actor === "dependabot[bot]"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get PR info
        id: get_pr_info
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/get-pr-info.js');
            await require(scriptPath)(github, context, core);
      - name: Display PR info
        run: |
          echo "PR outputs - ${{ steps.get_pr_info.outputs }}"
          echo "PR number - ${{ steps.get_pr_info.outputs.prNumber }}"
      - name: Download artifact once bundlesize done
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr-upload-data.yml
          name: data-arctifact
          pr: ${{ steps.get_pr_info.outputs.prNumber }}
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Collect data
        id: collect_data
        run: echo "::set-output name=downloadedData::$(node ./.github/workflows/download-cross-workflow-artifact.js)"
      - name: Post results to Log console
        run: echo "The downloaded ramdom number is ${{ steps.collect_data.outputs.downloadedData }}"
      - name: "Writing comments"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/writing-comments.js');
            const writingData = ${{ steps.collect_data.outputs.downloadedData }};
            await require(scriptPath)(github, context, core, writingData);