name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  upload-first-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display pr info
        # pull_request properties:
        # Doc: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
        run: |
          # Ref: https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286/2
          # Ref: https://github.community/t/github-sha-but-how-to-get-the-latest-commit-reference-on-a-branch/17160/2
          echo "PR commit  - ${{ github.event.pull_request.head.sha }}"
          echo "Merge commit - ${{ github.sha }}"
          # Note 1: equal to access variable `process.env.GITHUB_SHA` in the github-script
          # Note 2: expression `${ GITHUB_SHA }` is illegal
          echo "Merge commit - ${GITHUB_SHA}"
          echo "Merge commit - $GITHUB_SHA"
          echo "Repo - ${GITHUB_REPOSITORY}"
      - name: Generate data
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/generate-data.js');
            const filename = "generated-first-data.txt";
            await require(scriptPath)(github, context, core, filename);
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: first-data-arctifact
          path: generated-first-data.txt
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
  upload-second-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/generate-data.js');
            const filename = "generated-second-data.txt";
            await require(scriptPath)(github, context, core, filename);
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: second-data-arctifact
          path: generated-second-data.txt
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
