name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  upload-first-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/generate-data.js');
            const filename = "generated-first-data.txt";
            await require(scriptPath)(github, context, core, filename);
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: first-data-arctifact
          path: generated-first-data.txt
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
  upload-second-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/generate-data.js');
            const filename = "generated-second-data.txt";
            await require(scriptPath)(github, context, core, filename);
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: second-data-arctifact
          path: generated-second-data.txt
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
