name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  dependabot-comments:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15.4"
      - name: "Writing comments"
        uses: actions/github-script@v4
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/writing-comments.js');
            await require(scriptPath)(github, context, core);