name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  upload-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data
        id: generate_data
        run: |
          mkdir downloads
          cd downloads
          echo "$(node ../.github/workflows/generate-data.js)" > generated-data.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: data-arctifact
          path: downloads
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
  dependabot-comments:
    runs-on: ubuntu-18.04
    # Key change: modify the permission for this job taht ran by dependabot
    # Doc: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      issues: write
      packages: read
      statuses: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15.4"
      - name: "Writing comments"
        uses: actions/github-script@v4
        with:
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/dependabot-comments/permission-key.js');
            await require(scriptPath)(github, context, core);
