name: pr

on:
  pull_request:
    branches:
      - master

jobs:
  upload-first-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data
        id: generate_data
        run: |
          mkdir downloads
          cd downloads
          echo "$(node ../.github/workflows/generate-data.js)" > generated-first-data.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: first-data-arctifact
          path: downloads
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
  upload-second-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate data
        id: generate_data
        run: |
          mkdir downloads
          cd downloads
          echo "$(node ../.github/workflows/generate-data.js)" > generated-second-data.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: second-data-arctifact
          path: downloads
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
