name: workflow run

# Since dependabot doesn't have write permission in event "pull_request", we have two options:
# (1) Event "pull_request_target"
#     This event runs in the context of the base of the pull request, rather than in the merge commit as the pull_request event does.
# Doc: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
# (2) Event "workflow_run"
#     This event occurs when a workflow run is requested or completed, and allows you to execute a workflow based on the finished result of another workflow.
# Doc: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
# See [detail](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)
on:
  # This workflow run runs after the workflow "pr" is completed
  # Example: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  workflow_run:
    workflows: ["pr"]
    types:
      - completed

jobs:
  # Just FYI, to allow dependabot writting comments,
  # I also tried create the octokit instance with GITHUB_TOEKN myself in pull_request event, but no luck.
  # See [this comment in PR #44](https://github.com/marilyn79218/react-lazy-show/pull/44#issuecomment-873803780)
  # Or [PR #58](https://github.com/marilyn79218/react-lazy-show/pull/58)
  dependabot-comments:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Display workflow info
        run: |
          echo "PR branch  - ${{ github.event.workflow_run.head_branch }}"
          echo "PR commit - ${{ github.event.workflow_run.head_sha }}"
      - name: Download artifact from other workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr-upload-data.yml
          # The artifact name comes from previous workflow "pr"
          name: data-arctifact
          # Doc: https://github.com/dawidd6/action-download-artifact#usage
          # Doc: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run
          branch: ${{ github.event.workflow_run.head_branch }}
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: "Writing comments"
        uses: actions/github-script@v4
        with:
          script: |
            // Just FYI, to import modules in the github-script,
            // see [ref](https://github.com/actions/github-script/issues/73#issuecomment-675469777)
            // Example: PR #44 and PR #58
            const path = require('path');
            const scriptPath = path.resolve('./.github/workflows/dependabot-comments/index.js');
            // Use SINGLE QUOTE when accessing a env variable inside of the github-script
            // Ref: https://github.com/actions/github-script/issues/143#issue-893411221
            // Ref: https://github.com/actions/github-script/issues/56#issuecomment-642188313
            const commitHash = '${{ github.event.workflow_run.head_sha }}';
            await require(scriptPath)(github, context, core, commitHash);